package Params::Validate::Strict::BNF;

use strict;
use warnings;
use Carp qw(croak);
use Exporter qw(import);
use Params::Validate::Strict qw(validate_strict);

our $VERSION = '0.01';
our @EXPORT_OK = qw(bnf_to_matcher);

my %_cache;

=head1 NAME

Params::Validate::Strict::BNF - compile a BNF grammar to a string matcher

=head1 SYNOPSIS

  use Params::Validate::Strict::BNF qw(bnf_to_matcher);

  my $matcher = bnf_to_matcher([
      '<greeting> ::= "hello" | "hi"',
  ]);
  $matcher->('hello');  # 1
  $matcher->('bye');    # 0

=head1 DESCRIPTION

Converts an arrayref of BNF grammar lines into a closure that tests whether
a string is a member of the language defined by that grammar.

Used internally by L<Params::Validate::Strict> when a schema rule includes a
C<bnf> key.  Results are cached by grammar content, so repeated calls with
the same grammar pay no compilation cost after the first call.

=head1 GRAMMAR FORMAT

Each element of the arrayref is either a rule definition or a continuation line.

=head2 Rule definition

  '<rule-name> ::= <alternatives>'

The left-hand side is a non-terminal name enclosed in angle brackets.
The right-hand side is one or more alternatives separated by C<|>.

=head2 Continuation lines

A line that contains no C<::=> is appended (with a space) to the preceding
rule's right-hand side.  This lets long rules span multiple array elements:

  '<telephone-number> ::= <country-code-opt> <area-code> <separator-opt>',
  '<central-office-code> <separator-opt> <station-code>',

=head2 Terminals

Literal text is enclosed in double quotes.  An empty terminal C<""> matches
the empty string (makes a production optional):

  '<sep> ::= "" | "-" | " "'

Backslash escapes inside terminals (e.g. C<"\"">) are passed through to the
compiled regex via C<quotemeta>, so no special treatment is needed for regex
metacharacters.

=head2 Non-terminals

References to other rules are enclosed in angle brackets: C<< <rule-name> >>.
Recursive rules are not supported and will raise an exception.

=head2 Start rule

The first rule defined in the grammar is the start rule.  A value must match
the language generated by that rule (anchored C<^...$>) to be accepted.

=head1 FUNCTIONS

=head2 bnf_to_matcher( \@grammar_lines )

Compiles the grammar and returns a matcher closure C<sub { ... }> that
accepts a single string argument and returns 1 if it belongs to the language,
0 otherwise.

Raises an exception if:

=over 4

=item * the argument is not an arrayref

=item * the grammar contains no rule definitions

=item * a non-terminal reference is not defined elsewhere in the grammar

=item * a recursive rule is detected

=back

=cut

sub bnf_to_matcher {
	my ($grammar_lines) = @_;

	validate_strict({
		input  => { grammar_lines => $grammar_lines },
		schema => {
			grammar_lines => {
				type => 'arrayref',
				min  => 1,
			},
		},
	});

	my $cache_key = join("\0", @$grammar_lines);
	return $_cache{$cache_key} if exists $_cache{$cache_key};

	my (%rules, @rule_order);
	my ($current_rule, $current_rhs);

	my $flush = sub {
		return unless defined $current_rule;
		$rules{$current_rule} = _parse_rhs($current_rhs);
	};

	for my $line (@$grammar_lines) {
		if($line =~ /^\s*(<[^>]+>)\s*::=\s*(.*)$/) {
			$flush->();
			$current_rule = $1;
			push @rule_order, $current_rule unless exists $rules{$current_rule};
			$current_rhs = $2;
		} elsif(defined $current_rule && $line =~ /\S/) {
			$current_rhs .= " $line";
		}
	}
	$flush->();

	croak 'bnf_to_matcher: no rules found in grammar' unless @rule_order;

	my $start    = $rule_order[0];
	my $regex_str = _rule_to_regex($start, \%rules, {});
	my $re        = qr/^(?:$regex_str)$/s;

	my $matcher = sub { defined($_[0]) && $_[0] =~ $re ? 1 : 0 };
	$_cache{$cache_key} = $matcher;
	return $matcher;
}

sub _parse_rhs {
	my $rhs = $_[0];
	my @alternatives;

	for my $alt (split /\s*\|\s*/, $rhs) {
		my @tokens;
		while($alt =~ /("(?:[^"\\]|\\.)*"|<[^>]+>)/g) {
			my $tok = $1;
			if($tok =~ /^"(.*)"$/s) {
				push @tokens, { type => 'terminal', value => $1 };
			} else {
				push @tokens, { type => 'nonterminal', name => $tok };
			}
		}
		push @alternatives, \@tokens;
	}
	return \@alternatives;
}

sub _rule_to_regex {
	my ($rule_name, $rules, $seen) = @_;
	croak "bnf_to_matcher: undefined rule '$rule_name' referenced in grammar"
		unless exists $rules->{$rule_name};
	croak "bnf_to_matcher: recursive rule '$rule_name' is not supported"
		if $seen->{$rule_name};

	local $seen->{$rule_name} = 1;

	my @alt_regexes;
	for my $alt (@{ $rules->{$rule_name} }) {
		my $alt_re = '';
		for my $tok (@$alt) {
			if($tok->{type} eq 'terminal') {
				$alt_re .= quotemeta($tok->{value});
			} else {
				$alt_re .= _rule_to_regex($tok->{name}, $rules, $seen);
			}
		}
		push @alt_regexes, $alt_re;
	}

	return @alt_regexes == 1
		? $alt_regexes[0]
		: '(?:' . join('|', @alt_regexes) . ')';
}

1;

__END__

=head1 SEE ALSO

L<Params::Validate::Strict>

=head1 AUTHOR

Nigel Horne E<lt>njh@nigelhorne.comE<gt>

=head1 LICENSE

Copyright 2026 Nigel Horne.

This program is released under the following licence: GPL2.
If you use it,
please let me know.

=cut
